theme: jekyll-theme-minimal
title: Seminar in Applied Microeconomics - Virtual Assembly and Discussion
description: Platform for faculty and researchers in India to present their work and get feedback from the applied micro community
